<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="VisualCat.App.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="../VisualCat.Application/VisualCat.Application.csproj" />
    <ProjectReference Include="../VisualCat.Infrastructure/VisualCat.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
