[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repository = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))

Add-Type -AssemblyName System.Drawing
# The icon itself is defined once, in the shared module, so the Google Play
# store icon generated by tools/generate-play-assets.ps1 cannot drift away from
# the icon the application ships.
Import-Module (Join-Path $PSScriptRoot 'VisualCat.Branding.psm1') -Force

function Save-PngIcon([string]$Path, [int]$Size) {
    $directory = Split-Path -Parent $Path
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
    $bitmap = New-VisualCatIconBitmap -Size $Size
    try { $bitmap.Save($Path, [Drawing.Imaging.ImageFormat]::Png) }
    finally { $bitmap.Dispose() }
}

function Save-PngBackedIco([string]$Path, [string]$PngPath) {
    $bytes = [IO.File]::ReadAllBytes($PngPath)
    $stream = [IO.File]::Create($Path)
    $writer = [IO.BinaryWriter]::new($stream)
    try {
        $writer.Write([uint16]0)
        $writer.Write([uint16]1)
        $writer.Write([uint16]1)
        $writer.Write([byte]0)
        $writer.Write([byte]0)
        $writer.Write([byte]0)
        $writer.Write([byte]0)
        $writer.Write([uint16]1)
        $writer.Write([uint16]32)
        $writer.Write([uint32]$bytes.Length)
        $writer.Write([uint32]22)
        $writer.Write($bytes)
    }
    finally {
        $writer.Dispose()
        $stream.Dispose()
    }
}

function Save-ExactCrop([string]$Source, [string]$Destination, [Drawing.Rectangle]$Crop, [int]$Width, [int]$Height, [Drawing.Imaging.ImageFormat]$Format) {
    $sourceImage = [Drawing.Image]::FromFile($Source)
    $result = [Drawing.Bitmap]::new($Width, $Height, [Drawing.Imaging.PixelFormat]::Format24bppRgb)
    $result.SetResolution(96, 96)
    $graphics = [Drawing.Graphics]::FromImage($result)
    try {
        $graphics.CompositingQuality = [Drawing.Drawing2D.CompositingQuality]::HighQuality
        $graphics.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.SmoothingMode = [Drawing.Drawing2D.SmoothingMode]::HighQuality
        $graphics.DrawImage($sourceImage, [Drawing.Rectangle]::new(0, 0, $Width, $Height), $Crop, [Drawing.GraphicsUnit]::Pixel)
        $result.Save($Destination, $Format)
    }
    finally {
        $graphics.Dispose()
        $result.Dispose()
        $sourceImage.Dispose()
    }
}

$appPng = Join-Path $repository 'src/VisualCat.App/Assets/visualcat-icon.png'
$desktopPng = Join-Path $repository 'src/VisualCat.Desktop/Assets/visualcat-icon-256.png'
$desktopIco = Join-Path $repository 'src/VisualCat.Desktop/Assets/visualcat.ico'
Save-PngIcon $appPng 256
Save-PngIcon $desktopPng 256
Save-PngBackedIco $desktopIco $desktopPng

$analysis = Join-Path $repository 'docs/assets/heatmap-analysis.jpg'
Save-ExactCrop $analysis (Join-Path $repository 'docs/assets/heatmap-hero.jpg') ([Drawing.Rectangle]::new(0, 112, 3840, 1920)) 1600 800 ([Drawing.Imaging.ImageFormat]::Jpeg)
Save-ExactCrop $analysis (Join-Path $repository 'docs/assets/social-preview.jpg') ([Drawing.Rectangle]::new(0, 112, 3840, 1920)) 1280 640 ([Drawing.Imaging.ImageFormat]::Jpeg)
